[package]

name = "beehive_core"
version = "0.1.0"

authors.workspace = true
edition.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]

# Docs
aquamarine = { version = "0.6", optional = true }

# Encoding
base64 = "0.22"
serde = { workspace = true }
serde_bytes = "0.11.15"

# Crypto
aead = "0.5.2"
blake3 = {version = "1.5" }
chacha20poly1305 = "0.10.1"
ed25519-dalek = { version = "2.1", features = ["rand_core", "serde"] }
signature = "2.2"
x25519-dalek = { version = "2.0", features = ["getrandom", "serde", "static_secrets"] }

# Error Handling
thiserror = { workspace = true }

# Utilities
generic-array = "1.1"
nonempty = "0.10.0"
rand = "0.8.5"
topological-sort = "0.2.2"

# Testing
proptest = { version = "1.5", optional = true }
proptest-derive = { version = "0.5.0", optional = true }

[features]
mermaid_docs = ["aquamarine"]
test_utils = ["proptest", "proptest-derive"]
